### ISSUE TITLE
Build fail :  method `Err` is not a member of trait `FromStr`

### ISSUE THREAD

**Issue by Yamakaky** [PistonDevelopers/piston-examples#148]

**Comment by bvssvni** [comment]
Can you post the full error message?

**Comment by bvssvni** [comment]
Possibly related to change in `FromStr` https://github.com/PistonDevelopers/gfx_voxel/issues/34

**Comment by Yamakaky** [comment]
Yes, it's the same problem.

**Comment by Potpourri** [comment]
`FromStr` is not used in none example. It seems that it was a problem in some dependency.
Any way, now all examples compiles ok.
