### ISSUE TITLE
Example gfx_cube: gfx::Frame has no function "new".

### ISSUE THREAD

**Issue by andrensegura** [PistonDevelopers/piston-examples#223]
Hey all,

After trying to build gfx_cube, I receive this error:

    [andre@localhost gfx_cube]$ cargo build
    Compiling piston-example-gfx_cube v0.0.0 (file:///home/andre/Workspace/rust/piston-examples/gfx_cube)
    src/main.rs:107:17: 107:32 error: type `gfx::render::target::Frame<_>` does not implement any method in scope named `new`
    src/main.rs:107     let frame = gfx::Frame::new(win_width as u16, win_height as u16);
                                    ^~~~~~~~~~~~~~~
    error: aborting due to previous error
    Could not compile `piston-example-gfx_cube`.

I was reading through the gfx source and it looks like empty() should be being called:
https://github.com/gfx-rs/gfx-rs/blob/master/src/render/target.rs

I tried changing the code from:
`let frame = gfx::Frame::new(win_width as u16, win_height as u16);`

to:
`let frame = gfx::Frame::empty(win_width as u16, win_height as u16);`

Then ran `cargo build` again. It compiled without issues.
However, it gives this when running:

    [andre@localhost gfx_cube]$ cargo build
    Compiling piston-example-gfx_cube v0.0.0 (file:///home/andre/Workspace/rust/piston-examples/gfx_cube)
    [andre@localhost gfx_cube]$ cargo run
         Running `target/debug/piston-example-gfx_cube`
    thread '<main>' panicked at 'assertion failed: output.get_mask().contains(mask)', /home/andre/.cargo/git/checkouts/gfx-rs-93bce98024942039/master/src/render/mod.rs:187
    An unknown error occurred

I don't think I know enough about Rust yet to see the problem. Why is the assertion failing? I don't see where the issue is stemming from. Excited to learn though :)

If I am doing anything wrong (or right) in submitting an issue this way please let me know. I'm pretty new to github, open source projects, and Rust, so tips/tricks/advice is more than appreciated. Thanks!

**Comment by zummenix** [comment]
@andrensegura You are right there is no method in `gfx::Frame` called `new` – example a bit outdated.
@mitchmindtree opened an issue: https://github.com/gfx-rs/gfx-rs/issues/686 related to panic.

**Comment by bvssvni** [comment]
This was fixed by https://github.com/PistonDevelopers/gfx_graphics/pull/202
