### ISSUE TITLE
Mismatched types

### ISSUE THREAD

**Issue by kinson** [PistonDevelopers/piston-examples#242]
When I try to build any of the examples I get two types of errors. The first is mismatched types, and the second is that a trait is not implemented for the open_gl library. I've attached a screen shot of the errors. This could be an error with my machine, but I'm too new to Rust to really know. 

![image](https://cloud.githubusercontent.com/assets/1526888/7868842/707137fe-0533-11e5-984c-c204342bca20.png)

**Comment by bvssvni** [comment]
This is because we switched to crates.io dependencies and the examples need to be updated. See https://github.com/PistonDevelopers/piston/issues/891

I'll update them.

**Comment by bvssvni** [comment]
I got "gfx_cube" and the "sprite" example updated, but it is getting too late here. Will work on this tomorrow.

**Comment by bvssvni** [comment]
The examples are now updated. Closing.
