### ISSUE TITLE
Demonstrate max_fps() and ups() usage

### ISSUE THREAD

**Issue by anmej** [PistonDevelopers/piston-examples#258]
It is hard to find out how to use those, took me a while to realize you need to do `for e in window.events().max_fps(120).ups(60) {`, and I still don't know where you can see the other methods.

**Comment by bvssvni** [comment]
For the other methods, see http://docs.piston.rs/piston/piston/event/struct.WindowEvents.html.

**Comment by anmej** [comment]
Thanks. BTW, where do I find the `events()` method?

**Comment by bvssvni** [comment]
Here http://docs.piston.rs/piston/piston/event/trait.Events.html.

**Comment by bvssvni** [comment]
You can use the search bar at the top to look for methods.
