### ISSUE TITLE
hello_world example shows black screen

### ISSUE THREAD

**Issue by gsingh93** [PistonDevelopers/piston-examples#282]
I ran the `hello_world` example and only saw a black screen, no text. This is on Arch Linux.

**Comment by bvssvni** [comment]
Can you change the background color?

**Comment by gsingh93** [comment]
Huh, yea I can, and it turns out the "Hello World" was just black. But it should be set to green from the code...

**Comment by gsingh93** [comment]
Here's a screenshot:
![selection_002](https://cloud.githubusercontent.com/assets/1012677/8603253/19ac1258-2645-11e5-98ac-7b4f60f3aff3.png)

**Comment by giogadi** [comment]
I just had this issue too. Is the colored text code not working properly?

**Comment by bvssvni** [comment]
I got black too...

**Comment by bvssvni** [comment]
A list of the places of interest to this bug:

- [ ] https://github.com/PistonDevelopers/piston-examples/blob/master/src/hello_world.rs#L26
- [ ] https://github.com/PistonDevelopers/graphics/blob/master/src/text.rs#L27
- [ ] https://github.com/PistonDevelopers/graphics/blob/master/src/text.rs#L38
- [ ] https://github.com/PistonDevelopers/graphics/blob/master/src/image.rs#L78
- [ ] https://github.com/PistonDevelopers/graphics/blob/master/src/image.rs#L123
- [ ] https://github.com/PistonDevelopers/gfx_graphics/blob/master/src/back_end.rs#L299

**Comment by bvssvni** [comment]
```
$rustc -V
rustc 1.3.0-nightly (16f64c388 2015-07-09)
```

**Comment by bvssvni** [comment]
Tested this on Rust 1.1 and it shows the same bug.

**Comment by bvssvni** [comment]
Both shaders looks right:

- [x] https://github.com/PistonDevelopers/shaders/blob/master/graphics2d/textured/120.glslf
- [x] https://github.com/PistonDevelopers/shaders/blob/master/graphics2d/textured/150_core.glslf

**Comment by bvssvni** [comment]
I've overridden gfx_graphics locally with .cargo/config and printed out the color before setting it in the shader parameter:

```
batch_uv.state = *draw_state;
batch_uv.params.texture.0 = texture.handle();
println!("TEST {:?}", *color);
batch_uv.params.color = *color;
```

It prints out `TEST [0, 1, 0, 1]`.

**Comment by bvssvni** [comment]
Overwriting rust.png with a colored image and running the image example:

![screen shot 2015-07-10 at 13 07 47](https://cloud.githubusercontent.com/assets/1743862/8617499/b4c98238-2704-11e5-8a1d-44b31a4f04fc.png)

**Comment by bvssvni** [comment]
Rendered with `Image::new_colored` set to green:

![screen shot 2015-07-10 at 13 10 55](https://cloud.githubusercontent.com/assets/1743862/8617548/21cf5c68-2705-11e5-8ef5-5bcbf0c7a897.png)

**Comment by bvssvni** [comment]
I suspect there is something wrong with the texture generated from a glyph.

- [x] https://github.com/PistonDevelopers/gfx_graphics/blob/master/src/glyph.rs#L62
- [x] https://github.com/PistonDevelopers/gfx_texture/blob/master/src/lib.rs#L87
- [ ] https://github.com/PistonDevelopers/texture/blob/master/src/ops.rs#L21 (found the bug)

**Comment by bvssvni** [comment]
Fixed by https://github.com/PistonDevelopers/texture/pull/30

**Comment by gsingh93** [comment]
I don't understand the fix. What was the problem?

**Comment by bvssvni** [comment]
@gsingh93 `cargo update` should fix it. It rendered black pixels because when converting from a 8-bit alpha texture into rgba8 the rgba components were set to 0. By setting them to 255 the output color from the fragment shader multiplied with the uniform color becomes the color of the text.
