### ISSUE TITLE
bug - Compiling piston-gfx_texture v0.3.0 - error: internal compiler errorthread 'rustc' panicked at 'no entry found for key', ../src/libcore\option.rs:332

### ISSUE THREAD

**Issue by ScottHuangZL** [PistonDevelopers/piston-examples#302]
Compiling piston-gfx_texture v0.3.0
error: internal compiler errorthread 'rustc' panicked at 'no entry found for key', ../src/libcore\option.rs:332

: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
Could not compile `piston-gfx_texture`.

To learn more, run the command again with --verbose.
[Finished in 1.0s]

**Comment by boghison** [comment]
This has been fixed in rustc

**Comment by ScottHuangZL** [comment]
Thank you, I will try it later.
