### ISSUE TITLE
Piston projects won't compile on 64 bit Windows

### ISSUE THREAD

**Issue by kookerus** [PistonDevelopers/piston-examples#326]
When attempting to compile an Piston project on Windows x64, I get an issue with a file called miniz.c, which apparently doesn't support x64. Is there any way around this?

**Comment by mbrubeck** [comment]
I believe this is caused by GCC not including 64-bit support.  More details at https://www.reddit.com/r/rust_gamedev/comments/3v5vpq/piston_projects_wont_compile_on_x64_windows/cxkk68i

**Comment by kookerus** [comment]
Thanks. I saw that and just got an x64 compiler installed. I could've sworn I mine was 64 bit, but apparently not. Sorry for wasting your time.
