### ISSUE TITLE
Update sprite example for new API

### ISSUE THREAD

**Issue by svenstaro** [PistonDevelopers/piston-examples#331]
The API seems to have changed and I don't quite know how to incorporate the changes.

**Comment by panicbit** [comment]
I'm currently updating all of the example to get them working with the latest Piston release.
Here is the updated sprite.rs: https://github.com/panicbit/piston-examples/blob/6b516ed4bfc31e3b33d96698e1b67d085301c1f4/src/sprite.rs

**Comment by bvssvni** [comment]
@panicbit Looks right!
