### ISSUE TITLE
examples refuse to compile (outdated?)

### ISSUE THREAD

**Issue by bluecereal** [PistonDevelopers/piston-examples#336]
attempting to cargo run the examples gives the error: thread '< main >' panicked at 'called `Result::unwrap()` on an `Err` value: "Couldn\'t find any pixel format that matches the criterias.

i used cargo run --bin 'example_name'.  code was cloned via git, so typos aren't the issue.  what did i do wrong?  are the examples out of date?

**Comment by mitchmindtree** [comment]
Just thought I'd mention we're getting [the same issue](https://github.com/PistonDevelopers/conrod/issues/705) in conrod's examples.

**Comment by bvssvni** [comment]
This could be an issue with sRGB.

@bluecereal Do you have any info about the platform and graphics hardware you're using?

**Comment by bluecereal** [comment]
CPU: AMD FX8350 
GPU: R9 290x
RAM: 8GB DDR3
OS: Ubuntu 14.04
I recall setting sRGB to false and still getting the same error.

**Comment by bvssvni** [comment]
Does the "user_input" or "freetype" example works for you?

The piston_window overrides sRGB to true, because it uses gfx_graphics. The "user_input" and "freetype" example uses opengl_graphics. The opengl_graphics also enabled sRGB at the moment, but you might get an different error.

**Comment by csherratt** [comment]
Could this be a result of https://github.com/tomaka/glutin/issues/748 ? Basically glutin requires a GLX_ARB_framebuffer_sRGB or else it will fail to create a context if sRGB was requested.

**Comment by bluecereal** [comment]
I got a different error when trying to compile user_input and freetype.

note: /usr/bin/ld: cannot find -lSDL2
/usr/bin/ld: cannot find -lSDL2
collect2: error: ld returned 1 exit status

**Comment by bluecereal** [comment]
after installing SDL i get a different error when running freetype or user_input

thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "SDL error: Could not create GL context"', ../src/libcore/result.rs:688

the examples in the src directory give the same errors theyve given previously

**Comment by pierrechevalier83** [comment]
The original reported issue:  "Couldn\'t find any pixel format that matches the criterias." is fixed with commit 9df60172e0cf7e719760b2022991a51ae42b2a7c.

I can't reproduce the issue with user_input and free_type locally.

**Comment by cooperra** [comment]
I built this project today and everything worked.

**Comment by nicholasguyett** [comment]
I'm experiencing the same issues.  Running from ubuntu (bash on windows) via X server.

After seeing the second comment in this issue, I tried running the examples for conrod and got the same exact error.

**Comment by bluecereal** [comment]
If I remember correctly, disabling srgb did nothing unless it was done through a WindowSettings for some reason (as opposed to the normal PistonWindow::new() builder pattern), which is basically what the code below does.  
Although, I have been out of the Piston loop for a while now, so this code may be outdated.  This issue was caused by something to do with gfx (i think?).  kvark takes good care of that crate, all the more reason to assume this is a non-issue.    

```fn main() {
    let mut window: PistonWindow = {
        let title = "Hello, World!";
        let resolution = [640, 640];
        let opengl = OpenGL::V3_2;
        let mut window_result = WindowSettings::new(title, resolution)
            .exit_on_esc(true)
            .srgb(true)                      //try to init windowbuilder with srgb enabled
            .opengl(opengl)
            .build();
        if window_result.is_err() {   //if srgb=true fails, retry as srgb=false
            window_result = WindowSettings::new(title, resolution)
                .exit_on_esc(true)
                .srgb(false)                 //!!!
                .opengl(opengl)
                .build();
        }
        PistonWindow::new(opengl, 0, window_result
            .unwrap_or_else(|e| {
                panic!("Failed to build PistonWindow: {}", e)
            }))
    };```

Closed unless suggested otherwise.

**Comment by spiveeworks** [comment]
weird that the default behaviour of the "convenience wrapper" is to crash when forced settings can't be applied, but thanks for the solution/workaround!
