### ISSUE TITLE
Upgrade to gfx 0.12.0

### ISSUE THREAD

**Issue by jamescgibson** [PistonDevelopers/piston-examples#356]
On my machine, there's some opengl issue which prevents any of the examples from running. I talked to the gfx folks on Gitter, and since I can run the gfx examples in gfx 0.12.0, they consider this a solved issue.

I tried just replacing gfx 0.11.0 with gfx 0.12.0 in Cargo.toml, but no luck. Would be great if piston-examples could be updated to rely on gfx 0.12.0. 

I'm very new to piston / rust / graphics programming in general, so not sure how helpful I can be.

**Comment by martinlindhe** [comment]
This issue seems to be resolved, https://github.com/PistonDevelopers/piston-examples/blob/master/Cargo.toml#L50

**Comment by bvssvni** [comment]
Thanks! Closing.

**Comment by jamescgibson** [comment]
Thanks!
