### ISSUE TITLE
我应该如何隐藏后台窗体？

### ISSUE THREAD

**Issue by 3442853561** [PistonDevelopers/piston-examples#361]
How could I close or hide the DOS windows?
我应该如何隐藏后台窗体？

**Comment by bombless** [comment]
参考
http://stackoverflow.com/questions/29763647/how-to-make-a-program-that-does-not-display-the-console-window
https://github.com/rust-lang/rust/issues/29596
我用的是GNU ABI所以比如说编译hello_world的时候用的`cargo rustc --bin=hello_world --release -- -Clink-args="-mwindows"`

I'm using GNU ABI so I build hello_word with `cargo rustc --bin=hello_world --release -- -Clink-args="-mwindows"` for example

**Comment by bombless** [comment]
https://github.com/rust-lang/cargo/blob/2cda339cc23dda36ac247a34d28adcd30beead00/src/doc/config.md
I hope `[build.rustflags]` can help with this but it seems that it cannot be optional over build target ...
