### ISSUE TITLE
Build examples in src/ folder in CI

### ISSUE THREAD

**Issue by johnthagen** [PistonDevelopers/piston-examples#395]
It would be good to build the examples in the `src` directory with CI to make sure they stay in sync with the latest changes in Piston.

I believe an easy way to do this would be to move them into an `examples/` directory and build with `--example`: http://doc.crates.io/guide.html#project-layout

**Comment by bvssvni** [comment]
I thought they were built with Travis CI?

**Comment by johnthagen** [comment]
Upon closer inspection of the build log, I was mistaken. They are built with Travis. Sorry for the false alarm.
