### ISSUE TITLE
Tiled example

### ISSUE THREAD

**Issue by TatriX** [PistonDevelopers/piston-examples#398]
I did a [simple example](https://github.com/TatriX/rs-tiled-piston-example) which shows how to render a simple map from the [tiled](http://www.mapeditor.org/) editor.

I hope it may be useful as a "real world" example.

Also I would appreciate a comment on the `piston` usage.

**Comment by bvssvni** [comment]
Perhaps you want to use `Image::src_rect` instead of changing the scissors?

**Comment by TatriX** [comment]
Oh, I think I get it. I'll update the code.

**Comment by TatriX** [comment]
Much better now, thanks!

**Comment by bvssvni** [comment]
Do you want to make a PR?

**Comment by TatriX** [comment]
Can we add it as a submodule or I should do a copy of it to the repo?

**Comment by bvssvni** [comment]
A copy would be nice!

**Comment by TatriX** [comment]
Done: #399
