### ISSUE TITLE
Image sample triggers Windows Security

### ISSUE THREAD

**Issue by cgbeutler** [PistonDevelopers/piston-examples#448]
Running the example "image.exe" triggers a Windows Security issue
![image](https://user-images.githubusercontent.com/9751923/66680139-0ac6e080-ec2d-11e9-9457-1d166907ac0b.png)
I am guessing this is being triggered by a library or something. Wanted to start a paper trail for posterity. Not sure if this maybe needs a mini investigation to see if this needs to be passed on to piston core or something to make sure unsafe code is not used, just in case. Don't want cargo or piston to get a bad name ;)

**Comment by bvssvni** [comment]
You are the first one that reports a windows security trigger of this kind. There is no unsafe code in the Piston core, so the problem is not there.

**Comment by cgbeutler** [comment]
Bleh, I have poked at that thing for over an hour now. Windows Defender is so confusing and crappy. I really can't figure out what's happening with it. To make it even more confusing, image.exe seems to do a subset of what the others samples do, but they don't trigger anything. I'll dig again a little later.

**Comment by bvssvni** [comment]
Perhaps there is something wrong with the image library. You can open up an issue here: https://github.com/image-rs/image

**Comment by cgbeutler** [comment]
That's also used by several other samples. My first thought was that find_folder may be using an unsafe credential checker, but most other samples that use an image also use find_folder. Ill try messing more with it. Hopefully I can figure it out.
