### ISSUE TITLE
Please update the dependencies for the tiled example

### ISSUE THREAD

**Issue by willowell** [PistonDevelopers/piston-examples#451]
OS: macOS 10.15.1
rustc: 1.38.0

The tiled example fails to build through cargo because the cocoa v0.9.2 dependency fails to compile, producing this error:
`error[E0282]: type annotations needed
   --> /Users/$(name)/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.9.2/src/appkit.rs:479:9
    |
479 |         msg_send![self, releaseGlobally];
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |         |
    |         cannot infer type
    |         consider giving `result` a type
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)`

According to the pull requests for the cocoa crate, this issue was resolved very recently: https://github.com/servo/core-foundation-rs/pull/342

I also tried just bumping up piston, piston_window, and tiled in the Cargo.toml file for the tiled example, but that led to compilation errors in main.rs instead of in the dependencies. For instance, rustc said that the closure on line 41: `window.draw_2d(&e, |c, g| {` requires three arguments, but it got only two.

**Comment by bvssvni** [comment]
`|c, g, _|` should work.
